package config

const (
	ASSETS                                              = "Aktiva"
	PASSIVE                                             = "Pasiva"
	CATEGORY_CURRENT_ASSET                              = "Aktiva Lancar"
	CATEGORY_FIXED_ASSET                                = "Aktiva Tetap"
	CATEGORY_EQUITY                                     = "Modal"
	CATEGORY_SALES                                      = "Penjualan"
	CATEGORY_EXPENSE                                    = "Pengeluaran"
	CATEGORY_RECEIVABLE                                 = "Piutang"
	CATEGORY_DEBT                                       = "Hutang"
	CATEGORY_OPERATING                                  = "Operasional"
	CATEGORY_PRODUCTION_COST                            = "Biaya Produksi"
	CATEGORY_PURCHASE_RETURNS                           = "Return Pembelian"
	CATEGORY_SALES_RETURNS                              = "Return Penjualan"
	CATEGORY_PURCHASE_DISCOUNTS                         = "Diskon Pembelian"
	CATEGORY_COST_OF_REVENUE                            = "Beban Pokok Pendapatan"
	CATEGORY_OTHER_INCOME                               = "Pendapatan Lainnya"
	TYPE_TRANSFER                                       = "Transfer"
	TYPE_ASSET                                          = "Asset"
	TYPE_EQUITY                                         = "Equity"
	TYPE_INCOME                                         = "Income"
	TYPE_EXPENSE                                        = "Expense"
	TYPE_RECEIVABLE                                     = "Receivable"
	TYPE_LIABILITY                                      = "Liability"
	TYPE_PAYABLE                                        = "Payable"
	TYPE_COST                                           = "Cost"
	CASH_BANK_VALUE                                     = "Kas & Bank"
	CASH_BANK                                           = "cash_bank"
	CASHFLOW_GROUP_DEPRECIATION_AMORTIZATION_VALUE      = "Depresiasi & Amortisasi"
	CASHFLOW_GROUP_DEPRECIATION_AMORTIZATION            = "depreciation_amortization"
	CASHFLOW_GROUP_FIXED_ASSET_VALUE                    = "Aktiva Tetap"
	CASHFLOW_GROUP_CURRENT_ASSET_VALUE                  = "Aktiva Lancar"
	CASHFLOW_GROUP_FIXED_ASSET                          = "fixed_asset"
	CASHFLOW_GROUP_CURRENT_ASSET                        = "current_asset"
	CASHFLOW_GROUP_FINANCING                            = "financing"
	CASHFLOW_GROUP_OPERATING                            = "operating"
	CASHFLOW_GROUP_INVESTING                            = "investing"
	COGS                                                = "Harga Pokok Penjualan"
	COGS_ABBR                                           = "HPP"
	ACCOUNT_SUPPLY                                      = "Persediaan"
	BEGINNING_ACCOUNT_SUPPLY                            = "Persediaan Awal"
	PURCHASES                                           = "Pembelian"
	TOTAL_PURCHASES                                     = "Total Pembelian"
	TOTAL_DISCOUNT_PURCHASES                            = "Total Potongan Pembelian"
	NET_PURCHASES                                       = "Pembelian Bersih"
	OTHER_COST                                          = "Biaya Angkut dan Lain-lain"
	INVENTORY_AVALIABLE_SOLD                            = "Persediaan Tersedia Dijual"
	FINAL_ACCOUNT_SUPPLY                                = "Persediaan Akhir"
	GROSS_PROFIT                                        = "Laba Kotor"
	ACCOUNT_PROFIT_LOSS                                 = "Laba Rugi"
	RETAINED_EARNING                                    = "Laba Ditahan"
	OPERATING                                           = "operating"
	INVESTING                                           = "investing"
	FINANCING                                           = "financing"
	OPERATING_VALUE                                     = "Operasional"
	INVESTING_VALUE                                     = "Investasi"
	FINANCING_VALUE                                     = "Pendanaan"
	ACCEPTANCE_FROM_CUSTOMERS                           = "acceptance_from_customers"
	OTHER_CURRENT_ASSETS                                = "other_current_assets"
	PAYMENT_TO_VENDORS                                  = "payment_to_vendors"
	CREDIT_CARDS_AND_OTHER_SHORT_TERM_LIABILITIES       = "credit_cards_and_other_short_term_liabilities"
	OTHER_INCOME                                        = "other_income"
	OPERATIONAL_EXPENSES                                = "operational_expenses"
	ACCEPTANCE_FROM_CUSTOMERS_VALUE                     = "Penerimaan dari customer"
	OTHER_CURRENT_ASSETS_VALUE                          = "Aktiva lancar lainnya"
	PAYMENT_TO_VENDORS_VALUE                            = "Pembayaran ke vendor"
	CREDIT_CARDS_AND_OTHER_SHORT_TERM_LIABILITIES_VALUE = "Kartu kredit dan liabilitas jangka pendek lainnya"
	OTHER_INCOME_VALUE                                  = "Pendapatan lainnya"
	OPERATIONAL_EXPENSES_VALUE                          = "Pengeluaran operasional"
	ACQUISITION_SALE_OF_ASSETS                          = "acquisition_sale_of_assets"
	OTHER_INVESTMENT_ACTIVITIES                         = "other_investment_activities"
	ACQUISITION_SALE_OF_ASSETS_VALUE                    = "Perolehan/Penjualan aset"
	OTHER_INVESTMENT_ACTIVITIES_VALUE                   = "Aktivitas investasi lainnya"
	LOAN_PAYMENTS_RECEIPTS                              = "loan_payments_receipts"
	EQUITY_CAPITAL                                      = "equity_capital"
	LOAN_PAYMENTS_RECEIPTS_VALUE                        = "Pembayaran/Penerimaan pinjaman"
	EQUITY_CAPITAL_VALUE                                = "Ekuitas/Modal"
	RETURNS_PAYMENT_OF_TAXES                            = "returns_payment_of_taxes"
	RETURNS_PAYMENT_OF_TAXES_VALUE                      = "Pengembalian / Pembayaran pajak"
	PURCHASE_RETURN                                     = "PURCHASE_RETURN"
	SALES_RETURN                                        = "SALES_RETURN"
)

// AccountName AccountName
var AccountName map[string]string = map[string]string{
	TYPE_ASSET:      "Aset",
	TYPE_EQUITY:     "Modal",
	TYPE_INCOME:     "Pendapatan",
	TYPE_EXPENSE:    "Pengeluaran",
	TYPE_RECEIVABLE: "Piutang",
	TYPE_LIABILITY:  "Hutang",
	TYPE_COST:       "Biaya",
}

var DaysOfWeekAbbr = []string{"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"}

const (
	SALARY           = "SALARY"
	ALLOWANCE        = "ALLOWANCE"
	OVERTIME         = "OVERTIME"
	DEDUCTION        = "DEDUCTION"
	REIMBURSEMENT    = "REIMBURSEMENT"
	DRAFT            = "DRAFT"
	RUNNING          = "RUNNING"
	FINISHED         = "FINISHED"
	REQUEST          = "REQUEST"
	APPROVED         = "APPROVED"
	PAID             = "PAID"
	PROCESSING       = "PROCESSING"
	REJECTED         = "REJECTED"
	CANCELED         = "CANCELED"
	MONTH_MM         = "month-mm"
	MONTH_MMM        = "month-mmm"
	MONTH_MMMM       = "month-mmmm"
	YEAR_YYYY        = "year-yyyy"
	YEAR_YY          = "year-yy"
	AUTO_NUMERIC     = "auto-numeric"
	RANDOM_NUMERIC   = "random-numeric"
	RANDOM_CHARACTER = "random-character"
	STATIC_CHARACTER = "static-character"
	MONTH_ROMAN      = "month-roman"
)
